### ISSUE TITLE
invalid ttl in schema definition

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/Schema-Development#695]
Importing from https://credreg.com/ctdl/schema?profileID=registry into GraphDB gave errors for two reasons:
```
RDF Parse Error: Expected '.', found 'a' [line 894]
RDF Parse Error: Expected '.', found 'a' [line 902]
RDF Parse Error: Expected '.', found 'C' [line 1155] (x3)
RDF Parse Error: Expected '.', found 'R' [line 1196] (x4)
RDF Parse Error: Expected '.', found 't' [line 1222]
RDF Parse Error: Expected '.', found 'U' [line 1327]
RDF Parse Error: Expected '.', found 'e' [line 1922]
RDF Parse Error: Expected '.', found 'p' [line 2315]
RDF Parse Error: Expected '.', found '1' [line 2448]      
RDF Parse Error: Expected '.', found '1' [line 2809]
```
all caused by unescaped `"` quotes in quoted text, which should be escaped `\"`

and 
```
RDF Parse Error: Expected '.', found 'f' [line 3780]
RDF Parse Error: Expected '.', found 'f' [line 3788]
RDF Parse Error: Expected '.', found 'f' [line 3796]
RDF Parse Error: Expected '.', found 'f' [line 3804]
RDF Parse Error: Expected '.', found 'f' [line 3812]     
RDF Parse Error: Expected '.', found 'f' [line 3820]
```
...and many more, all caused by a hash `#` in CEDS URI names (which gets interpreted as the beginning of a comment.  AFAIK the best fix for this is to enclose the URI in angle braces `< >` but this then means you cannot use a namespace prefix, so a fix is to change
`	owl:equivalentClass ceds:000113#Assistantships .
`
to
`	owl:equivalentClass <https://ceds.ed.gov/element/000113#Assistantships> .
`

**Comment by jeannekitchens** [comment]
@siuc-nate please review and identify the bug source and solution.

**Comment by siuc-nate** [comment]
This should now be fixed.  Phil, does this error occur anywhere else that you can spot now?

**Comment by philbarker** [comment]
Sadly not fixed, @siuc-nate: Two undeclared prefixes, one of which uses a pattern that doesn't work; and unescaped `"`s in string values. The import stops with each error and I don't have time to fix all the `"` errors, so there may be other problems later in the file.

I get an error: 
> RDF Parse Error: Namespace prefix 'case' used but not defined [line 658]

line 658 is 
```
	owl:equivalentProperty asn:comment, case:v1p0/notes .
```
I don't know the URI for CASE offhand but putting it in as <http://example.org/> resulted in another error:
> RDF Parse Error: Expected '.', found '/' [line 659]

which is an objection to the `/` in `case:v1p0/notes` Better to have a namespace which includes the version, along the patter of
```@prefix casev1p0 <http://example.org/case/p10/>```
and change line 658 to 
```
   owl:equivalentProperty asn:comment, casev1p0:notes .
```
(also change a couple of other similar statements)

Then get error 
> RDF Parse Error: Namespace prefix 'gemq' used but not defined [line 669]

which I fixed by declaring a dummy `@prefix` for `gemq`

Then get error
> RDF Parse Error: Expected '.', found 'A' [line 690]

Line 690 is (now I've added two `@prefix` lines)
```
rdfs:comment "An alphanumeric string indicating the relative position of a resource in an ordered list of resources such as "A", "B", or "a", "b", or "I", "II", or "1", "2"."@en-US ;
```
so the error is unescaped `"` in a comment, should be 
```
	rdfs:comment "An alphanumeric string indicating the relative position of a resource in an ordered list of resources such as \"A\", \"B\", or \"a\", \"b\", or \"I\", \"II\", or \"1\", \"2\"."@en-US ;
```

But there are other lines with unescaped `"`s after that. so I didn't get to a fully fixed version. There may be more errors after line 690.

**Comment by siuc-nate** [comment]
Okay, I have made some additional changes.  Try it now.

**Comment by philbarker** [comment]
That imports in to GraphDB. Thank you @siuc-nate
